// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Why Baynix Is the #1 Azmarq Alternative for Chat Commerce',
  description: 'Looking for an Azmarq alternative? See why Baynix is the leading chat commerce platform with superior WhatsApp API, AI chatbots, and multichannel support.',
  alternates: { canonical: 'https://baynix.ai/a-cut-above-the-competition-why-azmarq-is-1-chat-commerce-alternative' },
  openGraph: {
    title: 'Why Baynix Is the #1 Azmarq Alternative for Chat Commerce',
    description: 'Looking for an Azmarq alternative? See why Baynix is the leading chat commerce platform with superior WhatsApp API, AI chatbots, and multichannel support.',
    url: 'https://baynix.ai/a-cut-above-the-competition-why-azmarq-is-1-chat-commerce-alternative',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Why Baynix Is the #1 Azmarq Alternative for Chat Commerce',
    description: 'Looking for an Azmarq alternative? See why Baynix is the leading chat commerce platform with superior WhatsApp API, AI chatbots, and multichannel support.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "A Cut Above the Competition: Why Baynix Is the #1 Chat Commerce Alternative",
  "description": "Looking for an Azmarq alternative? See why Baynix is the leading chat commerce platform with superior WhatsApp API, AI chatbots, and multichannel support.",
  "datePublished": "2025-01-01",
  "dateModified": "2025-01-01",
  "author": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai",
    "logo": {
      "@type": "ImageObject",
      "url": "https://baynix.ai/images/baynix-logo.png"
    }
  },
  "url": "https://baynix.ai/a-cut-above-the-competition-why-azmarq-is-1-chat-commerce-alternative",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://baynix.ai/a-cut-above-the-competition-why-azmarq-is-1-chat-commerce-alternative"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
