// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Click to WhatsApp Ads — Drive Conversions from Meta Ads',
  description: 'Convert Meta ad clicks directly into WhatsApp conversations. Baynix Click to WhatsApp Ads integrates seamlessly for lead capture and sales.',
  alternates: { canonical: 'https://baynix.ai/click-to-whatsapp-ads' },
  openGraph: {
    title: 'Click to WhatsApp Ads — Drive Conversions from Meta Ads',
    description: 'Convert Meta ad clicks directly into WhatsApp conversations. Baynix Click to WhatsApp Ads integrates seamlessly for lead capture and sales.',
    url: 'https://baynix.ai/click-to-whatsapp-ads',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Click to WhatsApp Ads — Drive Conversions from Meta Ads',
    description: 'Convert Meta ad clicks directly into WhatsApp conversations. Baynix Click to WhatsApp Ads integrates seamlessly for lead capture and sales.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Click to WhatsApp Ads",
  "description": "Convert Meta ad clicks directly into WhatsApp conversations. Baynix Click to WhatsApp Ads integrates seamlessly for lead capture and sales.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
