// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Communication Platform for Startups — Grow Faster with Baynix',
  description: 'Launch customer communication for your startup with Baynix. Affordable SMS, WhatsApp, and OTP APIs with flexible pricing and quick integration.',
  alternates: { canonical: 'https://baynix.ai/start-ups' },
  openGraph: {
    title: 'Communication Platform for Startups — Grow Faster with Baynix',
    description: 'Launch customer communication for your startup with Baynix. Affordable SMS, WhatsApp, and OTP APIs with flexible pricing and quick integration.',
    url: 'https://baynix.ai/start-ups',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Communication Platform for Startups — Grow Faster with Baynix',
    description: 'Launch customer communication for your startup with Baynix. Affordable SMS, WhatsApp, and OTP APIs with flexible pricing and quick integration.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Startup Communication",
  "description": "Launch customer communication for your startup with Baynix. Affordable SMS, WhatsApp, and OTP APIs with flexible pricing and quick integration.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
