// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Why RCS Is the Future of Customer Engagement',
  description: 'Discover why RCS messaging is transforming customer engagement and what brands must do to stay ahead. Rich media, verified senders, and conversational commerce.',
  alternates: { canonical: 'https://baynix.ai/why-rcs-messaging-is-the-future-of-customer-engagement-and-what-brands-must-do-next' },
  openGraph: {
    title: 'Why RCS Is the Future of Customer Engagement',
    description: 'Discover why RCS messaging is transforming customer engagement and what brands must do to stay ahead. Rich media, verified senders, and conversational commerce.',
    url: 'https://baynix.ai/why-rcs-messaging-is-the-future-of-customer-engagement-and-what-brands-must-do-next',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Why RCS Is the Future of Customer Engagement',
    description: 'Discover why RCS messaging is transforming customer engagement and what brands must do to stay ahead. Rich media, verified senders, and conversational commerce.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "Why RCS Messaging Is the Future of Customer Engagement and What Brands Must Do Next",
  "description": "Discover why RCS messaging is transforming customer engagement and what brands must do to stay ahead. Rich media, verified senders, and conversational commerce.",
  "datePublished": "2025-01-01",
  "dateModified": "2025-01-01",
  "author": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai",
    "logo": {
      "@type": "ImageObject",
      "url": "https://baynix.ai/images/baynix-logo.png"
    }
  },
  "url": "https://baynix.ai/why-rcs-messaging-is-the-future-of-customer-engagement-and-what-brands-must-do-next",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://baynix.ai/why-rcs-messaging-is-the-future-of-customer-engagement-and-what-brands-must-do-next"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
