// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'E-Commerce & D2C Communication — Order & Delivery Alerts',
  description: 'Drive sales and reduce returns with Baynix for E-Commerce. Automate order confirmations, shipping updates, abandoned cart recovery, and WhatsApp commerce.',
  alternates: { canonical: 'https://baynix.ai/e-commerce-d2c' },
  openGraph: {
    title: 'E-Commerce & D2C Communication — Order & Delivery Alerts',
    description: 'Drive sales and reduce returns with Baynix for E-Commerce. Automate order confirmations, shipping updates, abandoned cart recovery, and WhatsApp commerce.',
    url: 'https://baynix.ai/e-commerce-d2c',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'E-Commerce & D2C Communication — Order & Delivery Alerts',
    description: 'Drive sales and reduce returns with Baynix for E-Commerce. Automate order confirmations, shipping updates, abandoned cart recovery, and WhatsApp commerce.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix E-Commerce Communication",
  "description": "Drive sales and reduce returns with Baynix for E-Commerce. Automate order confirmations, shipping updates, abandoned cart recovery, and WhatsApp commerce.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
