// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'SMPP Platform — Enterprise SMPP Connectivity',
  description: 'Connect via SMPP to Baynix\'s carrier-grade messaging platform. High-throughput, low-latency SMPP service for telecoms, aggregators, and enterprises.',
  alternates: { canonical: 'https://baynix.ai/smpp-platform' },
  openGraph: {
    title: 'SMPP Platform — Enterprise SMPP Connectivity',
    description: 'Connect via SMPP to Baynix\'s carrier-grade messaging platform. High-throughput, low-latency SMPP service for telecoms, aggregators, and enterprises.',
    url: 'https://baynix.ai/smpp-platform',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SMPP Platform — Enterprise SMPP Connectivity',
    description: 'Connect via SMPP to Baynix\'s carrier-grade messaging platform. High-throughput, low-latency SMPP service for telecoms, aggregators, and enterprises.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix SMPP Platform",
  "description": "Connect via SMPP to Baynix's carrier-grade messaging platform. High-throughput, low-latency SMPP service for telecoms, aggregators, and enterprises.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
