// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'OTP API — Fast & Reliable One-Time Password API',
  description: 'Send OTP messages instantly via SMS, WhatsApp, or voice with Baynix OTP API. High delivery rates, intelligent channel fallback, and low latency.',
  alternates: { canonical: 'https://baynix.ai/otp-api' },
  openGraph: {
    title: 'OTP API — Fast & Reliable One-Time Password API',
    description: 'Send OTP messages instantly via SMS, WhatsApp, or voice with Baynix OTP API. High delivery rates, intelligent channel fallback, and low latency.',
    url: 'https://baynix.ai/otp-api',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'OTP API — Fast & Reliable One-Time Password API',
    description: 'Send OTP messages instantly via SMS, WhatsApp, or voice with Baynix OTP API. High delivery rates, intelligent channel fallback, and low latency.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix OTP API",
  "description": "Send OTP messages instantly via SMS, WhatsApp, or voice with Baynix OTP API. High delivery rates, intelligent channel fallback, and low latency.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
