// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'What Is RCS Messaging? Complete 2026 Guide',
  description: 'Everything you need to know about RCS messaging in 2026. How RCS works, advantages over SMS, business use cases, and how to get started with Baynix.',
  alternates: { canonical: 'https://baynix.ai/what-is-rcs-messaging-and-how-does-it-work-2026-guide' },
  openGraph: {
    title: 'What Is RCS Messaging? Complete 2026 Guide',
    description: 'Everything you need to know about RCS messaging in 2026. How RCS works, advantages over SMS, business use cases, and how to get started with Baynix.',
    url: 'https://baynix.ai/what-is-rcs-messaging-and-how-does-it-work-2026-guide',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'What Is RCS Messaging? Complete 2026 Guide',
    description: 'Everything you need to know about RCS messaging in 2026. How RCS works, advantages over SMS, business use cases, and how to get started with Baynix.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "What Is RCS Messaging and How Does It Work? 2026 Guide",
  "description": "Everything you need to know about RCS messaging in 2026. How RCS works, advantages over SMS, business use cases, and how to get started with Baynix.",
  "datePublished": "2025-01-01",
  "dateModified": "2025-01-01",
  "author": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai",
    "logo": {
      "@type": "ImageObject",
      "url": "https://baynix.ai/images/baynix-logo.png"
    }
  },
  "url": "https://baynix.ai/what-is-rcs-messaging-and-how-does-it-work-2026-guide",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://baynix.ai/what-is-rcs-messaging-and-how-does-it-work-2026-guide"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
