// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About Baynix — Our Mission, Vision & Story',
  description: 'Learn about Baynix, India\'s leading AI-powered business communication platform. Our mission, values, and the team building the future of customer engagement.',
  alternates: { canonical: 'https://baynix.ai/about' },
  openGraph: {
    title: 'About Baynix — Our Mission, Vision & Story',
    description: 'Learn about Baynix, India\'s leading AI-powered business communication platform. Our mission, values, and the team building the future of customer engagement.',
    url: 'https://baynix.ai/about',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'About Baynix — Our Mission, Vision & Story',
    description: 'Learn about Baynix, India\'s leading AI-powered business communication platform. Our mission, values, and the team building the future of customer engagement.',
  },
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
