// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'SMS Gateway — Carrier-Grade Message Routing',
  description: 'Route SMS through Baynix\'s enterprise SMS gateway. Direct carrier connections, intelligent routing, real-time delivery reports, and 99.9% uptime.',
  alternates: { canonical: 'https://baynix.ai/sms-gateway' },
  openGraph: {
    title: 'SMS Gateway — Carrier-Grade Message Routing',
    description: 'Route SMS through Baynix\'s enterprise SMS gateway. Direct carrier connections, intelligent routing, real-time delivery reports, and 99.9% uptime.',
    url: 'https://baynix.ai/sms-gateway',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SMS Gateway — Carrier-Grade Message Routing',
    description: 'Route SMS through Baynix\'s enterprise SMS gateway. Direct carrier connections, intelligent routing, real-time delivery reports, and 99.9% uptime.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix SMS Gateway",
  "description": "Route SMS through Baynix's enterprise SMS gateway. Direct carrier connections, intelligent routing, real-time delivery reports, and 99.9% uptime.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
