// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Number Masking — Protect Customer Privacy on Calls',
  description: 'Keep customer phone numbers private with Baynix Number Masking. Connect agents and customers without revealing real numbers — ideal for marketplaces.',
  alternates: { canonical: 'https://baynix.ai/number-masking' },
  openGraph: {
    title: 'Number Masking — Protect Customer Privacy on Calls',
    description: 'Keep customer phone numbers private with Baynix Number Masking. Connect agents and customers without revealing real numbers — ideal for marketplaces.',
    url: 'https://baynix.ai/number-masking',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Number Masking — Protect Customer Privacy on Calls',
    description: 'Keep customer phone numbers private with Baynix Number Masking. Connect agents and customers without revealing real numbers — ideal for marketplaces.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix Number Masking",
  "description": "Keep customer phone numbers private with Baynix Number Masking. Connect agents and customers without revealing real numbers — ideal for marketplaces.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
