// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Life at Baynix — Culture, Values & Team',
  description: 'Discover what makes Baynix a great place to work. Our culture, values, team events, and what life looks like inside India\'s growing communication tech company.',
  alternates: { canonical: 'https://baynix.ai/life-at-atpl' },
  openGraph: {
    title: 'Life at Baynix — Culture, Values & Team',
    description: 'Discover what makes Baynix a great place to work. Our culture, values, team events, and what life looks like inside India\'s growing communication tech company.',
    url: 'https://baynix.ai/life-at-atpl',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Life at Baynix — Culture, Values & Team',
    description: 'Discover what makes Baynix a great place to work. Our culture, values, team events, and what life looks like inside India\'s growing communication tech company.',
  },
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
