// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Voice OTP — Secure Phone Verification via Voice Call',
  description: 'Deliver one-time passwords via automated voice calls. Baynix Voice OTP ensures higher verification success rates than SMS for global users.',
  alternates: { canonical: 'https://baynix.ai/voice-otp' },
  openGraph: {
    title: 'Voice OTP — Secure Phone Verification via Voice Call',
    description: 'Deliver one-time passwords via automated voice calls. Baynix Voice OTP ensures higher verification success rates than SMS for global users.',
    url: 'https://baynix.ai/voice-otp',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Voice OTP — Secure Phone Verification via Voice Call',
    description: 'Deliver one-time passwords via automated voice calls. Baynix Voice OTP ensures higher verification success rates than SMS for global users.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix Voice OTP",
  "description": "Deliver one-time passwords via automated voice calls. Baynix Voice OTP ensures higher verification success rates than SMS for global users.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
