// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'RCS Messaging — Next-Gen Rich Business Messaging',
  description: 'Engage customers with RCS messages featuring images, carousels, quick replies, and verified sender badges. The future of mobile messaging.',
  alternates: { canonical: 'https://baynix.ai/rcs-messaging' },
  openGraph: {
    title: 'RCS Messaging — Next-Gen Rich Business Messaging',
    description: 'Engage customers with RCS messages featuring images, carousels, quick replies, and verified sender badges. The future of mobile messaging.',
    url: 'https://baynix.ai/rcs-messaging',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'RCS Messaging — Next-Gen Rich Business Messaging',
    description: 'Engage customers with RCS messages featuring images, carousels, quick replies, and verified sender badges. The future of mobile messaging.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix RCS Messaging",
  "description": "Engage customers with RCS messages featuring images, carousels, quick replies, and verified sender badges. The future of mobile messaging.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
