// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'IVR System — Interactive Voice Response for Business',
  description: 'Build multi-level IVR menus with Baynix. Route calls intelligently, automate phone support, and reduce agent workload with customisable IVR flows.',
  alternates: { canonical: 'https://baynix.ai/ivr-system' },
  openGraph: {
    title: 'IVR System — Interactive Voice Response for Business',
    description: 'Build multi-level IVR menus with Baynix. Route calls intelligently, automate phone support, and reduce agent workload with customisable IVR flows.',
    url: 'https://baynix.ai/ivr-system',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'IVR System — Interactive Voice Response for Business',
    description: 'Build multi-level IVR menus with Baynix. Route calls intelligently, automate phone support, and reduce agent workload with customisable IVR flows.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix IVR System",
  "description": "Build multi-level IVR menus with Baynix. Route calls intelligently, automate phone support, and reduce agent workload with customisable IVR flows.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
