// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Inbound Dialing Service — Handle Incoming Calls at Scale',
  description: 'Manage high volumes of inbound calls with Baynix. Smart call routing, queue management, and real-time analytics for inbound contact centres.',
  alternates: { canonical: 'https://baynix.ai/inbound-dialing-service' },
  openGraph: {
    title: 'Inbound Dialing Service — Handle Incoming Calls at Scale',
    description: 'Manage high volumes of inbound calls with Baynix. Smart call routing, queue management, and real-time analytics for inbound contact centres.',
    url: 'https://baynix.ai/inbound-dialing-service',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Inbound Dialing Service — Handle Incoming Calls at Scale',
    description: 'Manage high volumes of inbound calls with Baynix. Smart call routing, queue management, and real-time analytics for inbound contact centres.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Inbound Dialing Service",
  "description": "Manage high volumes of inbound calls with Baynix. Smart call routing, queue management, and real-time analytics for inbound contact centres.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
