// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Contact Baynix — Talk to Our Team',
  description: 'Get in touch with the Baynix team. Talk to our sales team, request a demo, or get technical support for our communication APIs.',
  alternates: { canonical: 'https://baynix.ai/contact' },
  openGraph: {
    title: 'Contact Baynix — Talk to Our Team',
    description: 'Get in touch with the Baynix team. Talk to our sales team, request a demo, or get technical support for our communication APIs.',
    url: 'https://baynix.ai/contact',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Contact Baynix — Talk to Our Team',
    description: 'Get in touch with the Baynix team. Talk to our sales team, request a demo, or get technical support for our communication APIs.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "ContactPage",
  "name": "Contact Baynix",
  "url": "https://baynix.ai/contact",
  "mainEntity": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai",
    "contactPoint": {
      "@type": "ContactPoint",
      "telephone": "+91-97739-81832",
      "contactType": "customer service",
      "email": "hello@baynix.ai",
      "availableLanguage": [
        "English",
        "Hindi"
      ]
    }
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
