// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Voice API — Programmable Voice Calls for Businesses',
  description: 'Integrate Baynix Voice API to build IVR, voice OTP, outbound campaigns, and call centre solutions. Crystal-clear audio and global reach.',
  alternates: { canonical: 'https://baynix.ai/voice-api' },
  openGraph: {
    title: 'Voice API — Programmable Voice Calls for Businesses',
    description: 'Integrate Baynix Voice API to build IVR, voice OTP, outbound campaigns, and call centre solutions. Crystal-clear audio and global reach.',
    url: 'https://baynix.ai/voice-api',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Voice API — Programmable Voice Calls for Businesses',
    description: 'Integrate Baynix Voice API to build IVR, voice OTP, outbound campaigns, and call centre solutions. Crystal-clear audio and global reach.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix Voice API",
  "description": "Integrate Baynix Voice API to build IVR, voice OTP, outbound campaigns, and call centre solutions. Crystal-clear audio and global reach.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
