// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'WhatsApp Chatbot — AI-Powered Automated Conversations',
  description: 'Build intelligent WhatsApp chatbots that handle support, sales, and FAQs 24/7. No-code and API-based WhatsApp bot builder for businesses.',
  alternates: { canonical: 'https://baynix.ai/whatsapp-chatbot' },
  openGraph: {
    title: 'WhatsApp Chatbot — AI-Powered Automated Conversations',
    description: 'Build intelligent WhatsApp chatbots that handle support, sales, and FAQs 24/7. No-code and API-based WhatsApp bot builder for businesses.',
    url: 'https://baynix.ai/whatsapp-chatbot',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'WhatsApp Chatbot — AI-Powered Automated Conversations',
    description: 'Build intelligent WhatsApp chatbots that handle support, sales, and FAQs 24/7. No-code and API-based WhatsApp bot builder for businesses.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix WhatsApp Chatbot",
  "description": "Build intelligent WhatsApp chatbots that handle support, sales, and FAQs 24/7. No-code and API-based WhatsApp bot builder for businesses.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
