// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Healthcare Communication Solutions — Patient Messaging',
  description: 'Improve patient engagement with HIPAA-compliant messaging. Baynix powers appointment reminders, health alerts, OTP verification, and teleconsultation.',
  alternates: { canonical: 'https://baynix.ai/health-care' },
  openGraph: {
    title: 'Healthcare Communication Solutions — Patient Messaging',
    description: 'Improve patient engagement with HIPAA-compliant messaging. Baynix powers appointment reminders, health alerts, OTP verification, and teleconsultation.',
    url: 'https://baynix.ai/health-care',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Healthcare Communication Solutions — Patient Messaging',
    description: 'Improve patient engagement with HIPAA-compliant messaging. Baynix powers appointment reminders, health alerts, OTP verification, and teleconsultation.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Healthcare Communication",
  "description": "Improve patient engagement with HIPAA-compliant messaging. Baynix powers appointment reminders, health alerts, OTP verification, and teleconsultation.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
