// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Email to SMS — Convert Emails to Text Messages',
  description: 'Send SMS from any email client with Baynix Email to SMS. Forward emails as text messages to customers without changing your existing workflow.',
  alternates: { canonical: 'https://baynix.ai/email-to-sms' },
  openGraph: {
    title: 'Email to SMS — Convert Emails to Text Messages',
    description: 'Send SMS from any email client with Baynix Email to SMS. Forward emails as text messages to customers without changing your existing workflow.',
    url: 'https://baynix.ai/email-to-sms',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Email to SMS — Convert Emails to Text Messages',
    description: 'Send SMS from any email client with Baynix Email to SMS. Forward emails as text messages to customers without changing your existing workflow.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix Email to SMS",
  "description": "Send SMS from any email client with Baynix Email to SMS. Forward emails as text messages to customers without changing your existing workflow.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
