// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'SMS Shortcode — Branded Short Codes for Mass Campaigns',
  description: 'Get a dedicated SMS shortcode for your brand. Baynix SMS Shortcode service offers 5–6 digit numbers ideal for marketing campaigns and voting.',
  alternates: { canonical: 'https://baynix.ai/shortcode' },
  openGraph: {
    title: 'SMS Shortcode — Branded Short Codes for Mass Campaigns',
    description: 'Get a dedicated SMS shortcode for your brand. Baynix SMS Shortcode service offers 5–6 digit numbers ideal for marketing campaigns and voting.',
    url: 'https://baynix.ai/shortcode',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SMS Shortcode — Branded Short Codes for Mass Campaigns',
    description: 'Get a dedicated SMS shortcode for your brand. Baynix SMS Shortcode service offers 5–6 digit numbers ideal for marketing campaigns and voting.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix SMS Shortcode",
  "description": "Get a dedicated SMS shortcode for your brand. Baynix SMS Shortcode service offers 5–6 digit numbers ideal for marketing campaigns and voting.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
