// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'EdTech Communication Platform — Student & Parent Messaging',
  description: 'Boost enrolments and engagement for your EdTech platform. Baynix delivers automated SMS, WhatsApp, and voice for admissions, attendance, and results.',
  alternates: { canonical: 'https://baynix.ai/edtech' },
  openGraph: {
    title: 'EdTech Communication Platform — Student & Parent Messaging',
    description: 'Boost enrolments and engagement for your EdTech platform. Baynix delivers automated SMS, WhatsApp, and voice for admissions, attendance, and results.',
    url: 'https://baynix.ai/edtech',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'EdTech Communication Platform — Student & Parent Messaging',
    description: 'Boost enrolments and engagement for your EdTech platform. Baynix delivers automated SMS, WhatsApp, and voice for admissions, attendance, and results.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix EdTech Communication",
  "description": "Boost enrolments and engagement for your EdTech platform. Baynix delivers automated SMS, WhatsApp, and voice for admissions, attendance, and results.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
