// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Conversational AI Chatbot — Intelligent Customer Automation',
  description: 'Deploy AI-powered chatbots across WhatsApp, SMS, RCS, and web. Automate support, qualify leads, and personalise every customer interaction.',
  alternates: { canonical: 'https://baynix.ai/conversational-ai-chatbot' },
  openGraph: {
    title: 'Conversational AI Chatbot — Intelligent Customer Automation',
    description: 'Deploy AI-powered chatbots across WhatsApp, SMS, RCS, and web. Automate support, qualify leads, and personalise every customer interaction.',
    url: 'https://baynix.ai/conversational-ai-chatbot',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Conversational AI Chatbot — Intelligent Customer Automation',
    description: 'Deploy AI-powered chatbots across WhatsApp, SMS, RCS, and web. Automate support, qualify leads, and personalise every customer interaction.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix Conversational AI Chatbot",
  "description": "Deploy AI-powered chatbots across WhatsApp, SMS, RCS, and web. Automate support, qualify leads, and personalise every customer interaction.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
