// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Email API — Transactional & Marketing Email at Scale',
  description: 'Send transactional, promotional, and bulk emails with Baynix Email API. High inbox delivery, real-time analytics, and SMTP or REST integration.',
  alternates: { canonical: 'https://baynix.ai/email-api' },
  openGraph: {
    title: 'Email API — Transactional & Marketing Email at Scale',
    description: 'Send transactional, promotional, and bulk emails with Baynix Email API. High inbox delivery, real-time analytics, and SMTP or REST integration.',
    url: 'https://baynix.ai/email-api',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Email API — Transactional & Marketing Email at Scale',
    description: 'Send transactional, promotional, and bulk emails with Baynix Email API. High inbox delivery, real-time analytics, and SMTP or REST integration.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix Email API",
  "description": "Send transactional, promotional, and bulk emails with Baynix Email API. High inbox delivery, real-time analytics, and SMTP or REST integration.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
