// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Enterprise Communication Solutions — Scalable Messaging APIs',
  description: 'Power your enterprise with Baynix. Carrier-grade SMS, WhatsApp Business API, and voice solutions with 99.9% uptime, dedicated support, and custom SLAs.',
  alternates: { canonical: 'https://baynix.ai/enterprises' },
  openGraph: {
    title: 'Enterprise Communication Solutions — Scalable Messaging APIs',
    description: 'Power your enterprise with Baynix. Carrier-grade SMS, WhatsApp Business API, and voice solutions with 99.9% uptime, dedicated support, and custom SLAs.',
    url: 'https://baynix.ai/enterprises',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Enterprise Communication Solutions — Scalable Messaging APIs',
    description: 'Power your enterprise with Baynix. Carrier-grade SMS, WhatsApp Business API, and voice solutions with 99.9% uptime, dedicated support, and custom SLAs.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Enterprise Communication",
  "description": "Power your enterprise with Baynix. Carrier-grade SMS, WhatsApp Business API, and voice solutions with 99.9% uptime, dedicated support, and custom SLAs.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
