// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Careers at Baynix — Join Our Team',
  description: 'Explore career opportunities at Baynix. Join a fast-growing AI communication company and help build the future of business messaging.',
  alternates: { canonical: 'https://baynix.ai/career' },
  openGraph: {
    title: 'Careers at Baynix — Join Our Team',
    description: 'Explore career opportunities at Baynix. Join a fast-growing AI communication company and help build the future of business messaging.',
    url: 'https://baynix.ai/career',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Careers at Baynix — Join Our Team',
    description: 'Explore career opportunities at Baynix. Join a fast-growing AI communication company and help build the future of business messaging.',
  },
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
