// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'WhatsApp Business API — Official WhatsApp API Provider',
  description: 'Get verified access to WhatsApp Business API. Send broadcasts, automate conversations, integrate chatbots, and drive sales over WhatsApp.',
  alternates: { canonical: 'https://baynix.ai/whatsapp-api' },
  openGraph: {
    title: 'WhatsApp Business API — Official WhatsApp API Provider',
    description: 'Get verified access to WhatsApp Business API. Send broadcasts, automate conversations, integrate chatbots, and drive sales over WhatsApp.',
    url: 'https://baynix.ai/whatsapp-api',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'WhatsApp Business API — Official WhatsApp API Provider',
    description: 'Get verified access to WhatsApp Business API. Send broadcasts, automate conversations, integrate chatbots, and drive sales over WhatsApp.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix WhatsApp Business API",
  "description": "Get verified access to WhatsApp Business API. Send broadcasts, automate conversations, integrate chatbots, and drive sales over WhatsApp.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
