// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'BFSI & Fintech Communication — Secure Financial Messaging',
  description: 'Secure, compliant messaging for banks, NBFCs, and fintechs. Baynix delivers OTP, fraud alerts, payment notifications, and loan updates at scale.',
  alternates: { canonical: 'https://baynix.ai/bsfi-fintech' },
  openGraph: {
    title: 'BFSI & Fintech Communication — Secure Financial Messaging',
    description: 'Secure, compliant messaging for banks, NBFCs, and fintechs. Baynix delivers OTP, fraud alerts, payment notifications, and loan updates at scale.',
    url: 'https://baynix.ai/bsfi-fintech',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BFSI & Fintech Communication — Secure Financial Messaging',
    description: 'Secure, compliant messaging for banks, NBFCs, and fintechs. Baynix delivers OTP, fraud alerts, payment notifications, and loan updates at scale.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix BFSI Fintech Communication",
  "description": "Secure, compliant messaging for banks, NBFCs, and fintechs. Baynix delivers OTP, fraud alerts, payment notifications, and loan updates at scale.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
