// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'OTP Authenticator — Multi-Channel OTP Verification Platform',
  description: 'Secure your users with Baynix OTP Authenticator. Multi-channel verification via SMS, voice, email, and WhatsApp with smart retry logic.',
  alternates: { canonical: 'https://baynix.ai/otp-authenticator' },
  openGraph: {
    title: 'OTP Authenticator — Multi-Channel OTP Verification Platform',
    description: 'Secure your users with Baynix OTP Authenticator. Multi-channel verification via SMS, voice, email, and WhatsApp with smart retry logic.',
    url: 'https://baynix.ai/otp-authenticator',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'OTP Authenticator — Multi-Channel OTP Verification Platform',
    description: 'Secure your users with Baynix OTP Authenticator. Multi-channel verification via SMS, voice, email, and WhatsApp with smart retry logic.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix OTP Authenticator",
  "description": "Secure your users with Baynix OTP Authenticator. Multi-channel verification via SMS, voice, email, and WhatsApp with smart retry logic.",
  "applicationCategory": "SecurityApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
