// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'WhatsApp CRM — Manage Customer Conversations at Scale',
  description: 'Manage all WhatsApp customer conversations from a single inbox. Assign chats, track pipeline, and close deals faster with Baynix WhatsApp CRM.',
  alternates: { canonical: 'https://baynix.ai/whatsapp-crm' },
  openGraph: {
    title: 'WhatsApp CRM — Manage Customer Conversations at Scale',
    description: 'Manage all WhatsApp customer conversations from a single inbox. Assign chats, track pipeline, and close deals faster with Baynix WhatsApp CRM.',
    url: 'https://baynix.ai/whatsapp-crm',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'WhatsApp CRM — Manage Customer Conversations at Scale',
    description: 'Manage all WhatsApp customer conversations from a single inbox. Assign chats, track pipeline, and close deals faster with Baynix WhatsApp CRM.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix WhatsApp CRM",
  "description": "Manage all WhatsApp customer conversations from a single inbox. Assign chats, track pipeline, and close deals faster with Baynix WhatsApp CRM.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
