// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Bulk SMS Service — Send Mass Text Messages at Scale',
  description: 'Send millions of SMS messages with Baynix Bulk SMS. High open rates, real-time delivery tracking, DND filtering, and carrier-direct routes.',
  alternates: { canonical: 'https://baynix.ai/bulk-sms' },
  openGraph: {
    title: 'Bulk SMS Service — Send Mass Text Messages at Scale',
    description: 'Send millions of SMS messages with Baynix Bulk SMS. High open rates, real-time delivery tracking, DND filtering, and carrier-direct routes.',
    url: 'https://baynix.ai/bulk-sms',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bulk SMS Service — Send Mass Text Messages at Scale',
    description: 'Send millions of SMS messages with Baynix Bulk SMS. High open rates, real-time delivery tracking, DND filtering, and carrier-direct routes.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Baynix Bulk SMS",
  "description": "Send millions of SMS messages with Baynix Bulk SMS. High open rates, real-time delivery tracking, DND filtering, and carrier-direct routes.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "INR"
  },
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  }
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
