// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Blog — Communication Insights & Guides',
  description: 'Explore the Baynix blog for expert insights on SMS, WhatsApp API, RCS messaging, chatbots, and business communication strategies.',
  alternates: { canonical: 'https://baynix.ai/blog' },
  openGraph: {
    title: 'Blog — Communication Insights & Guides',
    description: 'Explore the Baynix blog for expert insights on SMS, WhatsApp API, RCS messaging, chatbots, and business communication strategies.',
    url: 'https://baynix.ai/blog',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Blog — Communication Insights & Guides',
    description: 'Explore the Baynix blog for expert insights on SMS, WhatsApp API, RCS messaging, chatbots, and business communication strategies.',
  },
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
