// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Logistics Communication — Shipment Tracking & Delivery Alerts',
  description: 'Keep customers informed at every delivery milestone. Baynix Logistics Communication automates dispatch alerts, tracking updates, and POD confirmations.',
  alternates: { canonical: 'https://baynix.ai/logistics' },
  openGraph: {
    title: 'Logistics Communication — Shipment Tracking & Delivery Alerts',
    description: 'Keep customers informed at every delivery milestone. Baynix Logistics Communication automates dispatch alerts, tracking updates, and POD confirmations.',
    url: 'https://baynix.ai/logistics',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Logistics Communication — Shipment Tracking & Delivery Alerts',
    description: 'Keep customers informed at every delivery milestone. Baynix Logistics Communication automates dispatch alerts, tracking updates, and POD confirmations.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Logistics Communication",
  "description": "Keep customers informed at every delivery milestone. Baynix Logistics Communication automates dispatch alerts, tracking updates, and POD confirmations.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
