// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'SMS Longcode — Two-Way SMS with Long Virtual Numbers',
  description: 'Enable two-way SMS conversations with Baynix Longcode. Receive replies, run polls, and manage inbound SMS with dedicated long virtual numbers.',
  alternates: { canonical: 'https://baynix.ai/longcode' },
  openGraph: {
    title: 'SMS Longcode — Two-Way SMS with Long Virtual Numbers',
    description: 'Enable two-way SMS conversations with Baynix Longcode. Receive replies, run polls, and manage inbound SMS with dedicated long virtual numbers.',
    url: 'https://baynix.ai/longcode',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SMS Longcode — Two-Way SMS with Long Virtual Numbers',
    description: 'Enable two-way SMS conversations with Baynix Longcode. Receive replies, run polls, and manage inbound SMS with dedicated long virtual numbers.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix SMS Longcode",
  "description": "Enable two-way SMS conversations with Baynix Longcode. Receive replies, run polls, and manage inbound SMS with dedicated long virtual numbers.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
