// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Missed Call Service — Lead Generation via Missed Calls',
  description: 'Capture leads at zero cost to customers. Baynix Missed Call Service triggers instant callbacks, verifies users, and runs surveys via missed calls.',
  alternates: { canonical: 'https://baynix.ai/missed-call-service' },
  openGraph: {
    title: 'Missed Call Service — Lead Generation via Missed Calls',
    description: 'Capture leads at zero cost to customers. Baynix Missed Call Service triggers instant callbacks, verifies users, and runs surveys via missed calls.',
    url: 'https://baynix.ai/missed-call-service',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Missed Call Service — Lead Generation via Missed Calls',
    description: 'Capture leads at zero cost to customers. Baynix Missed Call Service triggers instant callbacks, verifies users, and runs surveys via missed calls.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Missed Call Service",
  "description": "Capture leads at zero cost to customers. Baynix Missed Call Service triggers instant callbacks, verifies users, and runs surveys via missed calls.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
