// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Voice Solutions — Cloud Telephony & Voice Messaging',
  description: 'Baynix Voice Solutions covers IVR, outbound dialling, voice OTP, number masking, and call analytics — all on one cloud telephony platform.',
  alternates: { canonical: 'https://baynix.ai/voice' },
  openGraph: {
    title: 'Voice Solutions — Cloud Telephony & Voice Messaging',
    description: 'Baynix Voice Solutions covers IVR, outbound dialling, voice OTP, number masking, and call analytics — all on one cloud telephony platform.',
    url: 'https://baynix.ai/voice',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Voice Solutions — Cloud Telephony & Voice Messaging',
    description: 'Baynix Voice Solutions covers IVR, outbound dialling, voice OTP, number masking, and call analytics — all on one cloud telephony platform.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Voice Solutions",
  "description": "Baynix Voice Solutions covers IVR, outbound dialling, voice OTP, number masking, and call analytics — all on one cloud telephony platform.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
