// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Media Coverage — Baynix in the News',
  description: 'Explore press coverage, media mentions, and news articles featuring Baynix. Stay updated with our latest milestones and announcements.',
  alternates: { canonical: 'https://baynix.ai/media-coverage' },
  openGraph: {
    title: 'Media Coverage — Baynix in the News',
    description: 'Explore press coverage, media mentions, and news articles featuring Baynix. Stay updated with our latest milestones and announcements.',
    url: 'https://baynix.ai/media-coverage',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Media Coverage — Baynix in the News',
    description: 'Explore press coverage, media mentions, and news articles featuring Baynix. Stay updated with our latest milestones and announcements.',
  },
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
