// generated by gen-seo
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Outbound Dialing Service — Automated Outbound Call Campaigns',
  description: 'Run high-volume outbound call campaigns with Baynix. Predictive, progressive, and preview dialers for sales, collections, and customer service.',
  alternates: { canonical: 'https://baynix.ai/outbound-dialing-service' },
  openGraph: {
    title: 'Outbound Dialing Service — Automated Outbound Call Campaigns',
    description: 'Run high-volume outbound call campaigns with Baynix. Predictive, progressive, and preview dialers for sales, collections, and customer service.',
    url: 'https://baynix.ai/outbound-dialing-service',
    siteName: 'Baynix',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Outbound Dialing Service — Automated Outbound Call Campaigns',
    description: 'Run high-volume outbound call campaigns with Baynix. Predictive, progressive, and preview dialers for sales, collections, and customer service.',
  },
}

const schema = {
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Baynix Outbound Dialing Service",
  "description": "Run high-volume outbound call campaigns with Baynix. Predictive, progressive, and preview dialers for sales, collections, and customer service.",
  "provider": {
    "@type": "Organization",
    "name": "Baynix",
    "url": "https://baynix.ai"
  },
  "areaServed": "IN",
  "serviceType": "Business Communication"
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      {children}
    </>
  )
}
